version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.5

references:
    workspace_root: &workspace_root
        /tmp/build

commands:
  setup:
    description: "Setup command to install/bootstrap/build"
    steps:
        - run: yarn install
        - run: yarn bootstrap
        - run: yarn build

#executors:
#    build-executor:
#        node/default


jobs:
  build-and-test:
    working_directory: *workspace_root
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - attach_workspace:
                at: /tmp/build
            - setup:
            - run:
                name: Test Code (lint, flow, jest)
                command: yarn test:ci
                environment:
                    JEST_JUNIT_OUTPUT_DIR: "reports/junit/js-test-results.xml"
            - store_test_results:
                path: reports/junit
            - store_artifacts:
                path: reports/junit
            - store_artifacts:
                path: .jest-coverage
            - persist_to_workspace:
                root: *workspace_root
                paths:
                  - .jest-coverage

  coverage:
    working_directory: *workspace_root
    executor:
      name: node/default
    steps:
      - node/with-cache:
          steps:
            - attach_workspace:
                at: /tmp/build
            - codecov/upload:
              file: .jest-coverage/coverage-final.json
              token: $CODECOV_TOKEN

workflows:
    build-and-test:
      jobs:
        - build-and-test
        - coverage:
            requires:
              - build-and-test
            filters:
              branches:
               only: master

#    build-and-deploy:
#      jobs:
#        - build-and-deploy:
#          filters:
#              branches:
#                  only: master
